### PR TITLE
feat: Icons can now be react elements

### PR DESCRIPTION
**Pull request by artalat**

### CODE REVIEW

**Comment by artalat** [comment]
@ammarkhan967 when can we close this?

**Comment by ammarkhan967** [comment]
@artalat planing it

**Comment by taha437** [comment]
@artalat  coverage  and travis pipeline  is fine why is this failing ?I cant find it

**Comment by artalat** [comment]
Here it is: https://codecov.io/gh/BlueBaseJS/plugin-material-ui/src/feature%2Ficons/src/components/BottomNavigationAction/BottomNavigationAction.tsx#L28

**Comment by taha437** [comment]
@artalat kindly review this.

**Pull request merged**
