### PR TITLE
fix(Fixed avatar Size and color issue): Fixed avatar size and color i…

### PR DESCRIPTION
**Pull request by Muzzamil75**

### CODE REVIEW

**Comment by artalat** [comment]
@ammarkhan967 when can we close this?

**Comment by ammarkhan967** [comment]
@artalat sir planning it

**Comment by taha437** [comment]
@artalat kindly review this PR

**Comment by artalat** [comment]
what is this PR are doing and why do we need it?

**Comment by artalat** [comment]
and does the current master still has this problem? since this seems to be an old PR maybe this issue was already fixed?

**Comment by ammarkhan967** [comment]
its released

**Pull request closed without merging**
